
    enum ParamIds {
        ENUMS(PARAM_AUX_NOISE_MIX,2),
        ENUMS(PARAM_BP_BW_ATV,0),
        ENUMS(PARAM_BP_BW_OFFSET,0),
        ENUMS(PARAM_BP_LEVEL_ATV,0),
        ENUMS(PARAM_BP_SHAPE_ATV,0),
        ENUMS(PARAM_BP_SHAPE_OFFSET,0),
        ENUMS(PARAM_ENV_ATV,4),
        ENUMS(PARAM_ENV_OFFSET,4),
        ENUMS(PARAM_FEEDBACK_ATV,0),
        ENUMS(PARAM_FM_ATV,0),
        ENUMS(PARAM_HP_BW_ATV,0),
        ENUMS(PARAM_HP_BW_OFFSET,0),
        ENUMS(PARAM_HP_LEVEL_ATV,0),
        ENUMS(PARAM_HP_SHAPE_ATV,0),
        ENUMS(PARAM_HP_SHAPE_OFFSET,0),
        ENUMS(PARAM_LP_BW_ATV,0),
        ENUMS(PARAM_LP_BW_OFFSET,0),
        ENUMS(PARAM_LP_LEVEL_ATV,0),
        ENUMS(PARAM_LP_SHAPE_ATV,0),
        ENUMS(PARAM_LP_SHAPE_OFFSET,0),
        ENUMS(PARAM_MATCH_ATV,0),
        ENUMS(PARAM_NOISE_ATV,2),
        ENUMS(PARAM_NOISE_BW_ATV,2),
        ENUMS(PARAM_NOISE_CURVE_SLOPE,0),
        ENUMS(PARAM_NOISE_LEVEL_ATV,0),
        ENUMS(PARAM_NOISE_MIX_OFFSET,0),
        ENUMS(PARAM_NOISE_MIX_WIDTH,0),
        ENUMS(PARAM_NOISE_SHAPE_ATV,2),
        ENUMS(PARAM_NOISE_SLOPE_ATV,2),
        ENUMS(PARAM_OUTPUT_LEVEL,0),
        ENUMS(PARAM_VOCT_ATV,0),
        NUM_PARAMS
    };
    enum InputIds {
        ENUMS(INPUT_AUX_NOISE,2),
        ENUMS(INPUT_BP_BW,0),
        ENUMS(INPUT_BP_LEVEL,0),
        ENUMS(INPUT_BP_SHAPE,0),
        ENUMS(INPUT_DELAY_CLOCK,0),
        ENUMS(INPUT_ENV,4),
        ENUMS(INPUT_EXT_ENV,0),
        ENUMS(INPUT_FEEDBACK,0),
        ENUMS(INPUT_FM,0),
        ENUMS(INPUT_GATE,0),
        ENUMS(INPUT_HP_BW,0),
        ENUMS(INPUT_HP_LEVEL,0),
        ENUMS(INPUT_HP_SHAPE,0),
        ENUMS(INPUT_LP_BW,0),
        ENUMS(INPUT_LP_LEVEL,0),
        ENUMS(INPUT_LP_SHAPE,0),
        ENUMS(INPUT_MATCH,0),
        ENUMS(INPUT_NOISE_BW,2),
        ENUMS(INPUT_NOISE_INPUT,0),
        ENUMS(INPUT_NOISE_LEVEL,0),
        ENUMS(INPUT_NOISE_MIX,0),
        ENUMS(INPUT_NOISE_SHAPE,2),
        ENUMS(INPUT_NOISE_SLOPE,2),
        ENUMS(INPUT_VOCT,0),
        NUM_INPUTS
    };
    enum OutputIds {
        ENUMS(OUTPUT_DELAY_IN,0),
        ENUMS(OUTPUT_DELAY_OUT,0),
        ENUMS(OUTPUT_ENV,0),
        ENUMS(OUTPUT_ENV_GATE,0),
        ENUMS(OUTPUT_NOISE,2),
        ENUMS(OUTPUT_NOISE_OUT,0),
        NUM_OUTPUTS
    };
    enum LightIds {

        NUM_LIGHTS
    };
    