
    enum ParamIds {
        ENUMS(PARAM_BIAS_CONTROL,1),
        ENUMS(PARAM_FREQ_LOCK,1),
        ENUMS(PARAM_GLITCH_BUTTON,1),
        ENUMS(PARAM_GLITCH_RATE,1),
        ENUMS(PARAM_LENGTH_CV_ATV,1),
        ENUMS(PARAM_LENGTH_FINE,1),
        ENUMS(PARAM_LENGTH_OFFSET,1),
        ENUMS(PARAM_PARAM_0_COARSE,1),
        ENUMS(PARAM_PARAM_0_CV_ATV,1),
        ENUMS(PARAM_PARAM_0_FINE,1),
        ENUMS(PARAM_PITCH_COARSE,1),
        ENUMS(PARAM_PITCH_FINE,1),
        ENUMS(PARAM_VOCT_ATV,1),
        NUM_PARAMS
    };
    enum InputIds {
        ENUMS(INPUT_EXT_CLK,1),
        ENUMS(INPUT_GLITCH_GATE,1),
        ENUMS(INPUT_LENGTH_CV,1),
        ENUMS(INPUT_PARAM_0_CV,1),
        ENUMS(INPUT_VOCT,1),
        NUM_INPUTS
    };
    enum OutputIds {
        ENUMS(OUTPUT_OUT,1),
        NUM_OUTPUTS
    };
    enum LightIds {
        ENUMS(LIGHT_LIGHT_CENTER,1),
        ENUMS(LIGHT_LIGHT_LEFT,1),
        ENUMS(LIGHT_LIGHT_RIGHT,1),
        NUM_LIGHTS
    };
    