
    enum ParamIds {
        ENUMS(PARAM_BIAS_CONTROL,1),
        ENUMS(PARAM_FREQ_LOCK,1),
        ENUMS(PARAM_GLITCH_BUTTON,1),
        ENUMS(PARAM_LENGTH_CV_ATV,1),
        ENUMS(PARAM_LENGTH_FINE,1),
        ENUMS(PARAM_LENGTH_OFFSET,1),
        ENUMS(PARAM_PARAM_0_COARSE,1),
        ENUMS(PARAM_PARAM_0_CV_ATV,1),
        ENUMS(PARAM_PARAM_1_COARSE,1),
        ENUMS(PARAM_PARAM_1_CV_ATV,1),
        ENUMS(PARAM_PARAM_ORDER,1),
        ENUMS(PARAM_PITCH_COARSE,1),
        ENUMS(PARAM_PITCH_FINE,1),
        NUM_PARAMS
    };
    enum InputIds {
        ENUMS(INPUT_EXT_CLK,1),
        ENUMS(INPUT_FREQ_LOCK_GATE,1),
        ENUMS(INPUT_GLITCH_GATE,1),
        ENUMS(INPUT_LENGTH_CV,1),
        ENUMS(INPUT_PARAM_0_CV,1),
        ENUMS(INPUT_PARAM_1_CV,1),
        ENUMS(INPUT_VOCT,1),
        NUM_INPUTS
    };
    enum OutputIds {
        ENUMS(OUTPUT_OUT,1),
        NUM_OUTPUTS
    };
    enum LightIds {

        NUM_LIGHTS
    };
    